HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS

export EDITOR=vim
export VISUAL=vim
export PAGER=less
export LESS='-R -F -X'

autoload -Uz colors && colors
export CLICOLOR=1

alias ll='ls -lah --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'

bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char

zstyle ':completion:*' menu select
autoload -Uz compinit && compinit

if command -v fzf >/dev/null 2>&1; then
  export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
fi

PROMPT='%F{cyan}%n%f:%F{yellow}%~%f$ '
